modLoader="javafml"
loaderVersion="[40,)"
license="Creative Commons Attribution-NonCommercial 3.0"

[[mods]]
modId="outletcraft"
version="1.0.0"
displayName="OutletCraft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Crule-Glare Prod"
description='''
beep boop skidibap fnf
'''

[[dependencies.outletcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




